package utils.errorhandling;
/**
 * Responsible to handle error type.
 */
public enum ErrorType
{
    SYNTAX_ERROR_VARNAME,
    SYNTAX_ERROR_NUMBER,
    SYNTAX_ERROR_PROGNAME,
    SYNTAX_ERROR_NOT_RECOGNIZED_CHARACTER,
    SYNTAX_ERROR,
    SYNTAX_ERROR_EXTRA_PAR,
    SYNTAX_ERROR_MULT,
    SYNTAX_ERROR_SUM,
    SYNTAX_ERROR_DIVIDE,
    SYNTAX_ERROR_MINUS,
    SYNTAX_ERROR_UNEXPECTED_CHAR,
    SYNTAX_ERROR_END_LINE
}
